repos:
  - repo: local
    hooks:
      - id: lint_rust
        name: Lint Rust
        entry: ./scripts/pre-commit/lint-rust.sh
        language: script
        types: ["rs"]
        pass_filenames: false

  - repo: local
    hooks:
      - id: format_rust
        name: Format Rust
        entry: ./scripts/pre-commit/format-rust.sh
        language: script

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
      - id: taplo-lint
