repos:
  - repo: local
    hooks:
      - id: lint_rust
        name: Lint Rust
        entry: ./scripts/pre-commit/lint_rust.sh
        language: script
        pass_filenames: false

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
      - id: taplo-lint
